services:
  - type: web
    name: virtual-tryon-backend
    env: node
    buildCommand: |
      npm install
      npm run build
    startCommand: npm start
    nodeVersion: 18.x
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000